# -*- coding: utf-8 -*-
"""WiseTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSukx08ewmiRhE3XU91_f6YA6IbwjQC5
"""

!pip install pyTelegramBotAPI
!pip install constants
!pip install schedule

import os
import schedule 
from multiprocessing import * 
import time 
import telebot
import datetime
import pytz
import random
import constants
import numpy
from telebot import types

token='5775993210:AAHb6Ai5HykFVNZZGyFCEL8hji9faf9XqjI'
bot=telebot.TeleBot(token)

@bot.message_handler(commands=['start'])
def start(message):
  mess=f'Привет, <b>{message.from_user.first_name}</b>. Выслушай мой рассказ.'
  bot.send_message(message.chat.id, mess, parse_mode='html')
  bot.send_photo(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/wise_tree.jpg','rb'))
  bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/Lightsideintro.ogg','rb'))
  markup=types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
  itema=types.KeyboardButton('Да ✅')
  itemb=types.KeyboardButton('Не хочу ❌')
  markup.add(itema,itemb)
  bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/Hoches li ti.ogg','rb'), reply_markup=markup)

@bot.message_handler(content_types=['text'])
def message_reply(message): 
  advices=['/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/advice/advice1.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/advice/advice2.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/advice/advice3.ogg', '/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/advice/advice4.ogg']
  advice=random.choice(advices)
  angry_mn=['/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree1.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree2.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree3.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree4.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree5.ogg','/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angrysliv/anrytree6.ogg']
  angry=random.choice(angry_mn)
  global delta2
  global zvanie
  zvanie=['Глупое семя', 'Смышленое семя','Думающий сорняк','Умный росток','Зеленый листок','Мудрое древо','Бешеное дерево','Дерево американский психопат','Древо Гослинг']
  
  if message.text=='Да ✅' or message.text== 'Я передумал, хочу начать испытание 😌 ':

    if message.text=='Я передумал, хочу начать испытание 😌 ':
      bot.send_message(message.chat.id,'*Дерево улыбается*')
    bot.send_photo(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/drevo_light.jpg','rb'))
    bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/ligtside_start.ogg','rb'))
    bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/helpbot.ogg','rb'))
    markup=types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    itema=types.KeyboardButton("Мой статус 📊")
    itemb=types.KeyboardButton("Совет от дерева 🤓")
    itemd=types.KeyboardButton("Начать отсчет ⏲️")
    markup.add(itema,itemb,itemd)
    bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/predosterezhenie.ogg','rb'), reply_markup=markup)
    
    global z
    z=False
    if z==False and message.text=='Мой статус 📊': 
      bot.send_message(message.chat.id, f'Дятел, сначала таймер запусти.')

  elif message.text=='Начать отсчет ⏲️':
    global start_watch
    start_watch = datetime.datetime.now(pytz.timezone('Europe/Moscow'))
    z=True
    #bot.send_message(message.chat.id, f'Твой результат {delta2.seconds} секунд')
    markup=types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    itema=types.KeyboardButton("Мой статус 📊")
    itemb=types.KeyboardButton("Совет от дерева 🤓")
    itemd=types.KeyboardButton("Я слился 👎")
    markup.add(itema,itemb,itemd)
    bot.send_message(message.chat.id, f'На часах {start_watch.strftime("%H:%M:%S")} по Москве, {start_watch.strftime("%d-%m-%Y")}. Я начал отсчет.', reply_markup=markup)

  elif z==False and message.text=='Мой статус 📊': 
    bot.send_message(message.chat.id, f'Дятел, сначала запусти отсчет.')
  elif z==True and message.text=='Мой статус 📊':
    bot.send_photo(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/drevo_light.jpg','rb'))
    stop_watch2 = datetime.datetime.now(pytz.timezone('Europe/Moscow'))
    delta2 = stop_watch2 - start_watch
    d2=delta2.total_seconds()
    d2el=int(d2//86400)
    if d2el <=1:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[0]}', parse_mode='html')
    if 1< d2el <=3:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[1]}', parse_mode='html')
    if 3< d2el <=7:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[2]}', parse_mode='html')
    if 7< d2el <=10:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[3]}', parse_mode='html') 
    if 10< d2el <=15:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[4]}', parse_mode='html')
    if 15< d2el <=30:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[5]}', parse_mode='html')
    if 30< d2el <=60:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[6]}', parse_mode='html')
    if 60< d2el <=90:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[7]}', parse_mode='html')
    if 90< d2el:
      bot.send_message(message.chat.id, '<b>Вот он, твой статус. \nКол-во дней:</b>'f'\n{d2el}<b>\nЗвание:</b> {zvanie[8]}', parse_mode='html')

  elif message.text=='Я слился 👎':
    z=False
    stop_watch = datetime.datetime.now(pytz.timezone('Europe/Moscow'))
    delta = stop_watch - start_watch
    d1=delta.total_seconds()
    d1elo=int(d1//86400)
    markup=types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    itema=types.KeyboardButton("Мой статус 📊")
    itemb=types.KeyboardButton("Совет от дерева 🤓")
    itemd=types.KeyboardButton("Начать отсчет ⏲️")
    markup.add(itema,itemb,itemd)
    bot.send_photo(message.chat.id,open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/drevo_dark.jpg','rb'),reply_markup=markup)
    bot.send_voice(message.chat.id, open(angry,'rb'))
    if d1elo % 10 == 1 and d1elo % 100 != 11:
      bot.send_message(message.chat.id, f'Того рот, ты продержался всего {d1elo} день?!')
    elif 2 <= d1elo % 10 <= 4 and (d1elo % 100 < 10 or d1elo % 100 >= 20):
      bot.send_message(message.chat.id, f'Того рот, ты продержался всего {d1elo} дня?!')
    else:
      bot.send_message(message.chat.id, f'Того рот, ты продержался всего {d1elo} дней?!')
  

  elif message.text=='Не хочу ❌':
      bot.send_photo(message.chat.id,open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/drevo_dark.jpg','rb'))
      markup=types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
      itema=types.KeyboardButton("Я передумал, хочу начать испытание 😌 ")
      markup.add(itema)
      bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/angry tree.ogg','rb'), reply_markup=markup)
  elif message.text=='Совет от дерева 🤓':
      bot.send_voice(message.chat.id, open(advice,'rb'))

@bot.message_handler(content_types=['photo'])
def get_user_photo(message):
  bot.send_voice(message.chat.id, open('/content/drive/MyDrive/Colab Notebooks/WiseTreeBot/losing_it.ogg','rb'))

bot.polling(none_stop=True)